### ISSUE TITLE
Update_Case not updating Case Severity

### ISSUE THREAD

**Issue by Pcktech** [TheHive-Project/TheHive4py#100]
### Request Type
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7
| OS version (client)       | Windows 10
| TheHive4py version / git hash   |  1.6.0

### Problem Description
api.update_case() does not update the Case Severity as expected even if severity is specified in fields=[].

On the otherhand, api.case.update(severity=1) does change the severity as expected.

### Steps to Reproduce
1. Create Class FakeName
2. Add id with default value of the Case ID
3. Add severity attribute default and/or use setattr after Step 4 to set the severity attribute value
4. fake_obj = FakeName()
5. Use api.update_case(fake_obj)

Other items (only tested CustomFields, Tags) update as expected using update_case, just not severity.

### Complementary information
Workaround: api.case.update() updates Severity, Custom Fields, and Tags. Others not tested at time of writing.

**Comment by nadouani** [comment]
Hello,

this code works:

```python
import json
from thehive4py.api import TheHiveApi

api = TheHiveApi('http://127.0.0.1:9000', 'XXXXXXXXXXXXxxx')

# Create a new case
case = api.case('XXXXXXXXXXXXX')

# Change some attributes of the new case
case.tlp = 3
case.severity = 3

# Update the case 
api.update_case(case)

# Update specific fields
api.update_case(case, fields=['severity', 'tlp'])

```

**Comment by GoJonnyGo970** [comment]
This works 👍 
from __future__ import unicode_literals
import json
import requests

from thehive4py.api import TheHiveApi
from thehive4py.models import *
#To use this script correctly please configure the following lines
         

api = TheHiveApi('yourURL','Your API Key')
 
def updatecase():
        for i in range(0,5000): #5000 is my upper end. I "unflag" all of my cases so I can do a mass delete
          
          case=api.get_case(i)
          if case.status_code==200:
            case.flag=False
            api.update_case(case,fields=['flag'])
          else:
            continue
