### ISSUE TITLE
Error - updating alert imported as a case

### ISSUE THREAD

**Issue by joseluratm** [TheHive-Project/TheHive4py#103]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)        | Ubuntu
| TheHive4py version      |  1.5.3

### Problem Description
When I made a update in a alert, with the 'update_alert' function, add the new "artifacts" and other things to the alert.

This is not a problem, the problem comes when this alert is imported as a case.
If I go to the case that has been generated, the artifacts that had the alert in this moment appear. But, if I update the alert, and add a new artifact, it is not updated in the case.

Do I have to update the case too?
If the alert that is imported as a case is of the MISP type, the case if it is updated when the alert artifacts change.

### Steps to Reproduce
1. Create a alert
2. Import as a case
3. Update alert
4. In the alert section, show that the alert has the new artifact
5. In the case doesn't appear this new artifact

Thanks you!!

**Comment by nadouani** [comment]
This is probably an issue in TheHive API... it needs investigation
