### ISSUE TITLE
Missing customFields handling from the Alert Class.

### ISSUE THREAD

**Issue by zambomarcell** [TheHive-Project/TheHive4py#106]
TheHive4py Alert modell dont get the customFields attribute.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  CentOS
| OS version (client)       | 7
| TheHive4py version / git hash   |  1.5.3

### Problem Description
TheHive4py Alert modell dont get the customFields attribute.

### Steps to Reproduce
1. get the official sample: https://github.com/TheHive-Project/TheHive4py/blob/master/samples/test-alert-create.py
2. run and compare output with the code (4 customFields in the example, 0 in the example code output)

### Possible Solutions
Call attributes.get('customFields', {} ) in the model.py/Class Alert()
```
--- /tmp/models.py      2019-02-03 17:50:39.156430066 +0100
+++ /usr/lib/python2.7/site-packages/thehive4py/models.py       2019-01-31 16:41:10.553107195 +0100
@@ -294,6 +294,7 @@
         self.date = attributes.get('date', int(time.time()) * 1000)
         self.tags = attributes.get('tags', [])
         self.caseTemplate = attributes.get('caseTemplate', None)
+        self.customFields = attributes.get('customFields', {} )
 
         self.title = self.attr(attributes, 'title', None, 'Missing alert title')
         self.type = self.attr(attributes, 'type', None, 'Missing alert type')
```

**Comment by nadouani** [comment]
This is fixed since last October https://github.com/TheHive-Project/TheHive4py/pull/87
