### ISSUE TITLE
FR: Download file from task log

### ISSUE THREAD

**Issue by PierreNei** [TheHive-Project/TheHive4py#112]
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04 TLS
| OS version (client)       | Ubuntu 18.04 TLS
| TheHive4py version / git hash   |  1.6.0

### Problem Description
Please add the API access to download files attached to a task log. From response['attachment']['id'] it would be great if we can call a method to actually download the file

I can have a go at it if you can point me to the information on how to get the file from the ID!

**Comment by nadouani** [comment]
The download link is like `https://SERVER:PORT/api/datastore/ATTACHMENT_ID?name=FILE_NAME`

**Comment by devinbfergy** [comment]
@nadouani Does this feature still need to be added? I wouldn't mind working on it. I will be adding a pull request in the next few days.

**Comment by nadouani** [comment]
@david-burkett Hello, please feel free to submit a PR for it I can take it in 1.8

**Comment by nadouani** [comment]
Closing this FR. It will be addressed by #204
