### ISSUE TITLE
promote_alert_to_case() doesn't apply caseTemplate

### ISSUE THREAD

**Issue by bangejsans** [TheHive-Project/TheHive4py#114]
### Request Type
Feature Request

### Request
There are certain alerts that will be promoted to a case 100% of the time. When I am using the promote_alert_to_case() method via thehivehooks to promote these alerts, the cases are created without using the caseTemplate field I set in the alert. Please update the method to include that option, or add a new method promote_alert_to_template_case()

**Comment by nadouani** [comment]
This is partially fixed by #115 and needs a fix in TheHive API, in version 3.4.0
