### ISSUE TITLE
support for case template deletion/creation

### ISSUE THREAD

**Issue by github-pba** [TheHive-Project/TheHive4py#124]
### Request Type
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       |  Debian
| TheHive4py version / git hash   |  unknown

### Problem Description
the current version os thehive4py seems to be missing support for creating and deleting case templates.

Since case templates are unsorted (see [TheHive #1006](https://github.com/TheHive-Project/TheHive/issues/1006)), we tried to completely destroy and recreate the case templates in a predictable order. 

This is not possible due to missing functions in TheHive4py

**Comment by nadouani** [comment]
TheHive4py is fact was not supposed to embark features related to administrative features, that's why there is no case template related APIs. That said, you can directly use the REST APIs that handles case templates. 

Is this an option?

**Comment by github-pba** [comment]
Yes, it is. I will directly call TheHive's API.
