### ISSUE TITLE
Querying for Cases that Contain Substring in Custom Field

### ISSUE THREAD

**Issue by verbecee** [TheHive-Project/TheHive4py#128]
Querying for Cases that Contain a Substring in Custom Field

Is it possible to use the find_cases function using a string that would be found in a larger string in a custom field? For example:

I have a custom field called "specialID", and some example values found in cases are "EXAMPLE123", "EXAMPLE489", and "DIFF1098." Is there a way to query for only cases that contain "EXAMPLE?" I have been able to find cases using the entire specialID, but cannot find cases using a substring.  Meaning,

query = {"_string": "customFields.specialID.string:'EXAMPLE123'"}

returns one case. The following query does not return any values:

query = {"_string": "customFields.specialID.string:'EXAMPLE'"}

I have also tried using "In" but that returns an Invalid query exception:

query = In("customFields.specialID.string", "EXAMPLE")

Thanks for your time, I appreciate any help!

**Comment by cndycc** [comment]
I am in a similar situation. Any update?

**Comment by nadouani** [comment]
Hello, what about 

```
query = ContainsString("customFields.specialID.string", "Example*")
```

or 

```
query = ContainsString("customFields.specialID.string", "Example*")
```
