### ISSUE TITLE
Create case Observables bug

### ISSUE THREAD

**Issue by MinhNamNguyen** [TheHive-Project/TheHive4py#132]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04.2
| TheHive4py version / git hash   |  1.6.0

### Problem Description
When i try to create an observable with the api that i deleted it, i got an error

### Steps to Reproduce
1. Create an observable
2. Delete it with thehive
3. Re create the exact same observable

### Complementary information
`ko: 400/{"type":"ConflictError","message":"Artifact already exists","object":{"tlp":1,"tags":[],"data":"http://test.com","ioc":false,"sighted":false,"message":null,"dataType":"url"}}`

`"createdBy": "admin",
        "data": "http://test.com",
        "dataType": "url",
        "id": "142bd7568b2d9e8c36edd6bce6041880",
        "ioc": false,
        "message": null,
        "reports": {},
        "sighted": false,
        "startDate": 1568710426791,
        "status": "Deleted",`

**Comment by i223t** [comment]
Same issue

**Comment by nadouani** [comment]
What version of TheHive are you using?

**Comment by i223t** [comment]
> What version of TheHive are you using?

3.3.0-1

**Comment by nadouani** [comment]
Hello, this used to be an issue in TheHive, but it's fixed at least in latest releases.
