### ISSUE TITLE
Allow passing in file-like objects to alert artifacts

### ISSUE THREAD

**Issue by jaredjennings** [TheHive-Project/TheHive4py#136]
At present, files are attached to Hive objects by passing filenames into TheHive4py functions and methods. #35 asks for the ability to pass in a file-like object instead, when creating a case observable, by passing in a `(file_object, filename_string)` tuple instead of just a filename. I want that functionality also for alert artifacts of `dataType` file.

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | bullseye/sid
| TheHive4py version / git hash   |  35762bbd

### Problem Description
I have an exchangelib message attachment object. It has an `fp` attribute, which is a file-like object. I want to make an alert artifact using the attachment's data, without bothering to save it to an actual file first. (This is parallel to #35, but for alert artifacts instead of case observables; the way these are sent is different.)

### Possible Solutions
Make the `_prepare_file_data` method of the `AlertArtifact` class accept a `(file_object, filename)` tuple, a little like #135.

**Comment by jaredjennings** [comment]
I have a branch for this (file-like-objects-for-alert-artifacts), but it is based on the file-like-objects-for-case-observables branch (PR #135) so if I were to make a PR now, you'd see some of the same changes here as there.

**Comment by nadouani** [comment]
This has been fixed in 1.8.0
