### ISSUE TITLE
Is TheHive4py still alive?

### ISSUE THREAD

**Issue by herrBez** [TheHive-Project/TheHive4py#141]
### Request Type
Info

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Any
| OS version (client)       | Any
| TheHive4py version / git hash   |  35762bbd50d8376943268464326b59c752d6241b

### Problem Description
- The last commit in the master branch is more than one year old. 
- The last commit in a branch (branch 1.x) is dated June 2019
- The 1.7.0 version milestone is due to 9 months 

### Possible Solutions
Clearly state if the project is still mantained or not.

**Comment by cyberpescadito** [comment]
Hello

The project is still maintained. The core developers team is very focused on the major update that will come in few days. TheHive4Py will also get updated & improved but no date announced. 
Be sure that except Hippocamp, the whole project is more than ever alive ! ;-)
