### ISSUE TITLE
Create case with the hive 4 rc1

### ISSUE THREAD

**Issue by mhutton81** [TheHive-Project/TheHive4py#144]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 9
| OS version (client)       | Windows 10
| TheHive4py version / git hash   |  Version 1.6.0

### Problem Description
When using the test-case-create.py and changing my systems variables i am getting the following error. 

Create Case
-----------------------------
ko: 404/{"type":"NotFoundError","message":"CustomField booleanField not found"}

### Steps to Reproduce
1. download and update the test-case-create.py script
2. run the python3 test-case-create.py script
3. see output from the running of the command.

### Complementary information
![error](https://user-images.githubusercontent.com/43049227/79241743-5189d300-7e28-11ea-8e75-453dfdae20d8.JPG)

**Comment by mhutton81** [comment]
not needed

**Comment by SantiagoSerrao** [comment]
Hi i am having the same issue

**Comment by SantiagoSerrao** [comment]
Sorry team i run the command with python3 and work find!

**Comment by Rodionc** [comment]
To avoid it, it's needed to user lowercase CustomField identificators, as it shown in 'Internal reference' field 
![image](https://user-images.githubusercontent.com/16780323/102120737-02cb8780-3e54-11eb-9778-f57e5afe4f5c.png)
