### ISSUE TITLE
Editing the application.conf file crashes theHive

### ISSUE THREAD

**Issue by aaronmartin1651** [TheHive-Project/TheHive4py#147]
Editing the application.conf file crashes theHive

### Request Type
Bug

### Work Environment

| Question                              | Answer
|---------------------------|--------------------
| OS version (server)            | Ubuntu
| OS version (client)             | 10
| TheHive4py version / git hash   |  RC1

### Problem Description
Editing the application.conf file crashes theHive

### Steps to Reproduce
1. modify the application.conf for https or ldap
2. restart service or computer
3. site won't come back up, even if you comment out the changes you just made.  If rebooted thehive service won't start automatically

### Possible Solutions
no idea

**Comment by nadouani** [comment]
This issue is not related to TheHive4py
