### ISSUE TITLE
FR: Allow specifying a custom `date` value for Alerts

### ISSUE THREAD

**Issue by vlabmichl** [TheHive-Project/TheHive4py#151]
In my use case I'm regularlly scanning a mailbox with a 5-min cronjob for mails that are parsed into TheHive `Alerts`.
=> Here it would be nice to be able to set the mails `sent` timestamp as the exact date value when the `Alert` was raised.

Actually that's not possible as the `Alert` date is always taken from the servers current date:
* https://github.com/TheHive-Project/TheHive4py/blob/35762bbd50d8376943268464326b59c752d6241b/thehive4py/models.py#L275

Just a minor feature request.

**Comment by nadouani** [comment]
Hello, `attributes.get('date', int(time.time()) * 1000)` means: if you provide a `date` when creating an `alert` then it will be taken, otherwise, we generate a date.

If it doesn't work as described above, then it's a bug somewhere.

Could you please confirm my assumptions?

**Comment by vlabmichl** [comment]
You're right it works as expected!
I didn't understand the code properly...
