### ISSUE TITLE
Add usage documentation

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive4py#153]
This issue aims to track the usage documentation progress:

- [x] Add mkdocs support
- [x] Deploy on gh-pages
- [x] Doc for API reference
- [ ] Doc for samples
- [x] Test all doc samples

**Comment by mrfreddi007** [comment]
Is the documentation updated for 2.0? I am only able to find documentation for 1.8

**Comment by Kamforka** [comment]
Hi @mrfreddi007 this thread is for v1.x which is legacy by now.
Unfortunately for v2.x the docs are not out yet.

**Comment by mrfreddi007** [comment]
> Hi @mrfreddi007 this thread is for v1.x which is legacy by now. Unfortunately for v2.x the docs are not out yet.

Okay, thank you

**Comment by Kamforka** [comment]
Will be continued in #291 and #301. Closing this one.
