### ISSUE TITLE
Add find_observables method

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive4py#157]
### Request Type
Feature Request

### Problem Description
Add a `find_observable` method to allow searching for observables, cross cases.

**Comment by dainok** [comment]
I found that get_case_observables can be used, but it requires a case.
```
        # Append the custom query if specified
        if "query" in attributes:
            criteria = And(parent_criteria, attributes["query"])
        else:
            criteria = parent_criteria
        data = {
            "query": criteria
        }
```

Can we make case_id optional? Or should we implement a find_observables?

**Comment by nadouani** [comment]
In general, I think that adding `find_observables` methods is needed, because it could be helpful in many use cases.
