### ISSUE TITLE
NameError: name 'requests' is not defined

### ISSUE THREAD

**Issue by gaglimax** [TheHive-Project/TheHive4py#163]
# NameError: name 'requests' is not defined

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker
| OS version (client)       | Docker
| TheHive4py version / git hash   |  ed7c6370f009ece57d6a76f6a60006dcd681e18e

### Problem Description
In file thehive4py/auth.py, you need to import requests. Else, an error occured
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/thehive4py/auth.py", line 24, in __call__
    req.headers['Authorization'] = requests.auth._basic_auth_str(self.username, self.password)
NameError: name 'requests' is not defined
```

### Steps to Reproduce
1. Execute the fonction

### Possible Solutions
import requests

**Comment by nadouani** [comment]
Hello, how did you install thehive4py? The error means you don't have the `requests` dependency

**Comment by gaglimax** [comment]
It is install via pip inside Docker.

In my script, I have the `requests` dependency. The issue comes from file : [thehive4py/auth.py](https://github.com/TheHive-Project/TheHive4py/blob/1.x/thehive4py/auth.py)

In line 24, the script is using `requests`, but the module is not imported at the beggining of the file.
You should add `import requests` before the line `from requests.auth import AuthBase`.

I have just created a pull requests : #168.
