### ISSUE TITLE
Documentation mismatch on function return

### ISSUE THREAD

**Issue by haam3r** [TheHive-Project/TheHive4py#165]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Mac
| TheHive4py version / git hash   |  1.7.1

### Problem Description

`api.find_first()` function should, according to doc strings return a `requests.Response` object. It however returns a regular Python dict.

Relevant lines in code: https://github.com/TheHive-Project/TheHive4py/blob/1.x/thehive4py/api.py#L433-L439

### Steps to Reproduce

```
case = api.find_first(query=query, sort=['-title'], range='all')

# This will fail
# print(case.json())

# This works
print(case)
```

### Possible Solutions

Two options:
1. Change documentation to say that the returned object is a dict of the case description.
2. Change the returned object to be of type `requests.Response`.

### Complementary information

Currently the first matched case is returned by selecting the first element in the JSON array returned by the search API. Would  it make more sense to instead set the range parameter to `range='0-1'`?

Happy to submit a PR for this, if a solution is decided upon.

**Comment by nadouani** [comment]
Hello @haam3r of course the `range` param must be fixed to `0-1`

**Comment by haam3r** [comment]
Ack I'll submit a PR against the 1.x branch
