### ISSUE TITLE
api.py python 2 - invalid syntax 

### ISSUE THREAD

**Issue by xxdesmus** [TheHive-Project/TheHive4py#176]
### Request Type: 
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu 20.04
| TheHive4py git hash   |  https://github.com/TheHive-Project/TheHive4py/commit/b2fdb7088e1821d4f1d045c268d20bef46398980
| Python2 version | Python 2.7.18rc1

### Problem Description
I'm trying to run [urlScan2Hive](https://github.com/notx11/urlScan2Hive) (which submits reports to urlscan.io and then pushes the observables into a case in Hive.

```
python2 urlScan.py -h
Traceback (most recent call last):
  File "urlScan.py", line 8, in <module>
    from thehive4py.api import TheHiveApi
  File "/usr/local/lib/python2.7/dist-packages/thehive4py/api.py", line 22
    def __init__(self, url: str, principal: str, organisation=None, password=None, proxies={}, cert=True):
                          ^
SyntaxError: invalid syntax
```

### Steps to Reproduce
1. `pip install thehive4py`
1. `git clone https://github.com/notx11/urlScan2Hive.git` 
1. `cd `urlScan2Hive`
1. add API key for urlscan.io to `urlScan.py`
1. `python2 urlScan.py`

### Complementary information
Based on the error it does not appear to be an issue with urlScan2Hive, but an issue with thehive4py (line 22). I'd love to say I could triage and fix this myself, but that looks to be well beyond my skill level.

**Comment by nadouani** [comment]
Hello @xxdesmus I don't think we would support Python 2 anymore, I'm sorry for that.

**Comment by xxdesmus** [comment]
Python3 also has an error (though a different one ->
```
python3 urlScan.py
  File "urlScan.py", line 84
    print '[*] Added URL observable for ' + i
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[*] Added URL observable for ' + i)?
```

```
python3 --version
Python 3.8.2
```
