### ISSUE TITLE
Missing function delete_case_task

### ISSUE THREAD

**Issue by gelim** [TheHive-Project/TheHive4py#190]
### Request Type

Feature Request

### Problem Description

Hi,
the ability to delete task seems to be missing.

My use-case for this may seems a bit cumbersome, and could need a new bug/feature request: I want to be able to attach informative files (not infected) ZIP,PDF,... to a case, and so that they will be visible on the case main page thus not doing a "file" observbable, but instead creating a dummy task, and inside a dummy task log with the file attached, then I'd like to cleanup the task. Attached files are kept, and visible in the front case page.

Cheers,

-- Mathieu
Amadeus CERT

**Comment by gelim** [comment]
PR#191 implements this task deletion feature (mimicked from browsser interaction when clicking on task's "Delete" button) with the patch `{"status":"Cancel"}` request.

**Comment by nadouani** [comment]
Thanks @gelim 

This issue and PR unveils an issue in TheHive that lists attachments from deleted tasks, which is wrong.

**Comment by gelim** [comment]
> TheHive that lists attachments from deleted tasks, which is wrong.

heh yes, I finally don't use this workaround and decided to handle attachment on an external webserver, and just build a markdown table listing the files + link in the case description. Additionally that allows me not clobber too much ES with file blobs.
All of that works of course as I just need to attach files at creation time.
