### ISSUE TITLE
Responder Creation Issue

### ISSUE THREAD

**Issue by gaj5** [TheHive-Project/TheHive4py#212]
# Responder Creation Issue

### Request Type
I am currently experiencing an odd issue which I believe might be a bug with a responder I am creating for thehive that requires data to be pulled from thehive and returned - I receive a proxy error upon attempting this. I have had numerous people review the code and suggest alternative things for this, but no success as of yet.

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Cortex docker 3.0.1-1
| OS version (client)       | TheHive docker 4.0.0-1
| TheHive4py version / git hash   |  TheHive4py 1.8.0

### Problem Description
The responder performs the simple task of extracting a case observable ('url') and importing it into an email to be sent. However, when I run the responder, I get the below error - we run our instance in front of an Nginx proxy:

<img width="947" alt="Screenshot_2021-02-10_at_10 39 53" src="https://user-images.githubusercontent.com/78970273/107788581-7ac90780-6d48-11eb-8e32-b93067805d6d.png">

### Steps to Reproduce

        from cortexutils.responder import Responder
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart
        from thehive4py.api import TheHiveApi
        from thehive4py.models import CaseObservable
        from thehive4py.query import Eq, And
        import ssl
        import sys
        import json
        import requests

        #Configure Mail Settings
        class email_phish_alert(Responder):
            def __init__(self):
            Responder.__init__(self)
            proxies = {'https': '***', 'http': '***'}
            api = TheHiveApi('*TheHive Address/Port*', '*API KEY*, proxies=proxies)

        #Build query
        query = And(Eq('dataType', 'url'), Eq('ioc', True))

        #Call the API to search all case's URL observables
        response = api.get_case_observables('case_id', query=query)

        #Display the result
        if response.status_code == 200:
            #Get response data
            list = response.json()

        else:
            print('Failure: {}/{}'.format(response.status_code, response.text))

I have removed the parts of the code relating to the emailing side of things, as that has been tested and is fine. The only issue remains with getting the data and pulling it to display. I have a feeling it could be linked to bug reported #201 however the format used in that code has not been successful for myself.

**Comment by mnmnc** [comment]
Does not look to me like responder creation issue. What you describe and what logs are showing (`403`) is that you have a proxy that requires authentication and you did not authorised your request properly.

**Comment by gaj5** [comment]
> Does not look to me like responder creation issue. What you describe and what logs are showing (`403`) is that you have a proxy that requires authentication and you did not authorised your request properly.

Unfortunately this is something I've tried - our proxy requires no authentication, and I've even tried specify that it doesn't use a username/password when passing through it, however the same issue persists.
