### ISSUE TITLE
Bad hyperlinks to models from API docs

### ISSUE THREAD

**Issue by ccrenfroe** [TheHive-Project/TheHive4py#222]
# Bad hyperlinks to [models](https://thehive-project.github.io/TheHive4py/reference/models/) from [API]( https://thehive-project.github.io/TheHive4py/reference/api/) docs
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Browser | Mozilla, Edge (yuck!)

### Problem Description
When clicking the hyperlinks to be taken to the docs for the various models used in the different methods, A 404 error is thrown!

Picture of webpage displayed on 404 

![hive_doc_Bad](https://user-images.githubusercontent.com/35737053/120511138-1d5cd300-c398-11eb-93a4-c100aeff07a9.png)

### Steps to Reproduce
1. Go to the [API](https://thehive-project.github.io/TheHive4py/reference/api/) docs
2. Find a function with a hyperlink to a model, say update_case. Click the link to a `Case`
3. Observe a 404 error as seen above.

### Possible Solutions
(keep this section if you have suggestions on how to solve the problem. **Otherwise delete it**)

I am assuming it is simply looking at the docs and making updates to links? I am ignorant of how your docs are set up though.

**Comment by nadouani** [comment]
Browsable documentation is deployed at: https://thehive-project.github.io/TheHive4py/
