### ISSUE TITLE
How to perform a bulk-insert of observables

### ISSUE THREAD

**Issue by aalini200** [TheHive-Project/TheHive4py#263]
I am an analyst and I created a case for a threat hunting project. I have 100+ IPs that I have to enter as observables in the HIVE. Is there a way to do a bulk insert instead of entering IPs one by one. Thanks.

**Comment by Kamforka** [comment]
Please take a look at the API docs under the section of [Create Alert](https://docs.strangebee.com/thehive/api-docs/#operation/Create%20Alert).
In case you want to do it with `thehive4py` you want to use the `TheHiveApi.alert.create` method.

**Comment by Kamforka** [comment]
I assume the above answered the original question.
