### ISSUE TITLE
Support cases page

### ISSUE THREAD

**Issue by cyberpescadito** [TheHive-Project/TheHive4py#273]
Hi :) 

Would it be possible to support case pages management in th4py 2 ? 
Many thanks !

Regards

**Comment by Kamforka** [comment]
Hi @cyberpescadito  is this what you refer to: https://docs.strangebee.com/thehive/api-docs/#tag/Page ?

**Comment by cyberpescadito** [comment]
hi @Kamforka , to be more precise, I'm talking about https://docs.strangebee.com/thehive/api-docs/#operation/Create%20a%20Page 
Both functions are almost identical but the one you mention is related to the Knowledge base, while the other one is for "pages" in cases

**Comment by Kamforka** [comment]
So to summarize, we need these methods implemented:

```python
hive.case.create_page(...) 
hive.case.delete_page(...)
hive.case.update_page(...)
```
Or am I missing something?

**Comment by Kamforka** [comment]
Done in #275
