### ISSUE TITLE
Adding Custom Tags

### ISSUE THREAD

**Issue by Freddy-pp** [TheHive-Project/TheHive4py#274]
Hi.
Is there any way to quickly add a large number of Custom Tags?
Thanks in advance.

**Comment by Kamforka** [comment]
Hi @Freddy-pp, without any nitpixking

**Comment by Freddy-pp** [comment]
Hi @Kamforka. Thank you for your answer.
Large in my case > 1000. Quick in my case means "not manually".)) Tags I want to add to Custom Tags https://docs.thehive-project.org/thehive/user-guides/organisation-managers/custom-tags/ so they are painted in a certain color. As far as I understand the API does not allow adding new tags to Custom Tags. But perhaps you know some other way to automate this. Or consider adding the ability to create and edit tags in Custom Tags as a Feature Request.
