### ISSUE TITLE
Inaccurate type definitions for alerts and procedures

### ISSUE THREAD

**Issue by ValEhk** [TheHive-Project/TheHive4py#277]
## Inaccurate type definition for alerts and procedures

Some of the types in `thehive4py/types/` are not correctly defined:
* `InputAlert` in `types/alert.py` is missing a `procedures` field;
* `InputProcedureRequired` in `types/procedure.py` contains a `tactic` field while this field is not actually required.

This is only a minor issue as it does not prevent creating alerts or interacting with TheHive, but type checking tools will return an error when the missing or wrongly categorized fields are used.
I've only encounter this issue with alers and procedures, but there might be similar issues for other types.

### Environment
|||
|:---|:---|
| OS version |  Ubuntu 20.04.5 LTS |
| thehive4py | 2.0.0b4 | 

### Steps to reproduce
```python
from thehive4py.client import TheHiveApi
from thehive4py.types.alert import InputAlert
from thehive4py.types.procedure import InputProcedure

if __name__ == "__main__":
    hive_client = TheHiveApi(
        url="<url>",
        apikey="<api_key>",
    )

    ttps: list[InputProcedure] = [{"patternId": "T1548", "occurDate": 1678970000}]
    alert: InputAlert = {
        "title": "Test alert",
        "description": "An alert to showcase the issue with the current types definitions",
        "type": "test",
        "source": "python",
        "sourceRef": "1",
        "procedures": ttps,
    }
    hive_client.alert.create(alert)
```

Running `mypy` for instance will return the 2 following errors:
```
error: Missing key "tactic" for TypedDict "InputProcedure"  [typeddict-item]
error: Extra key "procedures" for TypedDict "InputAlert"  [typeddict-unknown-key]
```

**Comment by Kamforka** [comment]
Fixed in #280
