### ISSUE TITLE
[Case] Ability to push observables as soon as the case is created

### ISSUE THREAD

**Issue by LetMeR00t** [TheHive-Project/TheHive4py#281]
Hi,

Today we can push observables within an alert but not within a case, is it something wanted ?

Alert: https://github.com/TheHive-Project/TheHive4py/blob/1655154c6d8ef2617719da2fc89050f71f18b6f7/thehive4py/types/alert.py#L29

Case (the only thing close to it without knowing how to use it): https://github.com/TheHive-Project/TheHive4py/blob/1655154c6d8ef2617719da2fc89050f71f18b6f7/thehive4py/types/case.py#L59

Could you provide a fix to have this feature as it's multiplying the number of API calls made

Thank you

**Comment by Kamforka** [comment]
Valid feature request, however it is related to the API rather then to the python client. 
@vdebergue can this one be taken up by the backend team rather than keeping it as a thehive4py issue?

**Comment by Kamforka** [comment]
@nadouani is there a better place to track such feature requests related to TheHive itself (rather than to thehive4py)?

**Comment by nadouani** [comment]
I agree this is not a thehive4py responsability as there is no API for it.

Allowing the creation of a case with a set of observables with a single API call can be dangerous. It's ok for a case having dozens of observables but we have already seen cases with thousands of IPs.

I suggest to close this issue and continue the discussion elsewhere @LetMeR00t ;)
