### ISSUE TITLE
Export (Reports, Notifications Integration (API) Incidents 

### ISSUE THREAD

**Issue by fasanches** [TheHive-Project/TheHive4py#285]
Dear support team,

Version: 4.1.24-1

I would like to report an issue I am experiencing while trying to download all incidents using the API with cURL.

When making the request to retrieve the incidents, I am encountering difficulties in receiving all the registered information, including tags and other relevant details.

Having complete access to the incidents is crucial for my work, as I need to properly analyze and process this data.

I would appreciate it if you could investigate this issue and provide guidance on how I can obtain all incidents with all the relevant information using the API and cURL or any other suitable method.

**curl.exe -H 'Authorization: Bearer [API_KEY_GERADA]' 'http://000.000.000.000:8767/api/case?range=all' > c:/temp/incidents.json**

Additionally, I would appreciate support with other matters such as integration with Office or even alert notifications.

I am available to provide further details or additional information if needed.

Thank you in advance for your attention and support.

**Comment by Kamforka** [comment]
Please reach out to the support team via help@strangebee.com.
Closing this issue as it is not related to the library itself.
