### ISSUE TITLE
find_cases() with ContainsStrings() not compatible with TH5

### ISSUE THREAD

**Issue by gelim** [TheHive-Project/TheHive4py#289]
Hello,

when testing TheHive4py with a TH5 (5.2.1-1) instance with some historical code working on TH4 I noticed that usage of `ContainsStrings()` was not supported anymore on TH5. Context is doing a `find_cases()`

The TheHive4py object `ContainsStrings("title", "Foobar")` was generating this error:

```
{'errors': [{'acceptedInput': ['query', 'parentChildFilter'],
             'field': 'FObject(Map(_wildcard -> FObject(Map(_field -> '
                      'FString(title), _value -> FString(*Foobar*)))))',
             'format': 'empty',
             'name': '_and[1]',
             'type': 'InvalidFormatAttributeError'},
[...]
```

It seems that using `Like()` instead fix this issue, so letting you know about that if anyone stumble on this.
You just need to add yourself the '*' around you search term.

The patch on my side that fixes this misbehavior (working on both 4 & 5 versions) for the `query` building part:

``` diff
-             [ContainsString("title", val) for val in args.title.split(" ")] +
+             [Like("title","*%s*" % val) for val in args.title.split(" ") if len(val) > 2] +
```

If there is any comment on this fix / how to do it even better, I'm listening :)
Cheers!

**Comment by Kamforka** [comment]
Hi @gelim and thank you very much for your input!
One thing I'm not sure about, where is the `ContainString` filter coming from exactly? I've checked the predefined filters in `thehive4py` and I don't see this declared anywhere in the lib.

When checking the docs of the [Query API](https://docs.strangebee.com/thehive/api-docs/#operation/Query%20API) for available filters there's no reference to any `_containsString` filter either, so I'd recommend using `_like` or `_match` (in case of a single word lookup).

```
Filters
Available filters:

_and: {"_and": [...other filters] }
_or: {"_or": [...other filters] }
_not: {"_not": { other filter } }
_any: {"_any": null} match any entities
_lt: {"_lt": {"_field": "<field>", "_value": <value>} less than
_gt: {"_gt": {"_field": "<field>", "_value": <value>} greater than
_lte: {"_lte": {"_field": "<field>", "_value": <value>} less than or equal
_gte: {"_gte": {"_field": "<field>", "_value": <value>} greater than or equal
_ne: {"_ne": {"_field": "<field>", "_value": <value>} not equal
_eq: {"_eq": {"_field": "<field>", "_value": <value>} equal
_is: {"_is": {"_field": "<field>", "_value": <value>} same as _eq
_startsWith: {"_startsWith": {"_field": "<field>", "_value": "<value>"} string starts with
_endsWith: {"_endsWith": {"_field": "<field>", "_value": "<value>"} string ends with
_id: {"_id": "~123"} filter by ID
_between: {"_between": {"_field": "<field>", "_from": <from>, "_to": <to>}} range filter, from is inclusive, to is exclusive, they are both mandatory
_in: {"_in": {"_field": "<field>", "_values": [<value1>, ...] }} the field is one of these values
_contains: {"_contains": "<field>"} if an object contains this field
_like: {"_like": {"_field": "<field>", "_value": "<value>"} the field (or a word, depending on the index type) contains the substring
_match: {"_match": {"_field": "<field>", "_value": "<value>"} the field contains the word
```

Hope it helps!

**Comment by gelim** [comment]
Ok, so I'm using TheHive4py 1.x branch, so it seems this `ContainsString` disappeared in main (was in `./thehive4py/query.py`)
I will test further with the latest code...

**Comment by Kamforka** [comment]
Closing it as it was more like of a version mismatch rather than a bug.
