### ISSUE TITLE
TheHive4py integration tests - No persistence for licensing

### ISSUE THREAD

**Issue by LetMeR00t** [TheHive-Project/TheHive4py#292]
Hello,

As a matter of fact, this library is using pytest in order to run unit test for integration.
However, in order to fully test the library, we need to have several organisations for tests purpose.
With the default community licence, we are limited to one organisation when the tests need to have at least two organisations so this implies to have a licence from StrangeBee in order to achieve all the tests.
A licence is required but we need to support persistence first for the licence (as a licence is linked to one instance and without persistence, we will need to get another licence everytime we run the tests).

In order to achieve the integration tests, we need to support persistence for licensing (with a database on a given volume).

**Comment by vdebergue** [comment]
Hello,

Exactly as @Kamforka said. 
As we have to manage license keys to restrict access to all the application features, this puts restrictions especially on this kind of environement.

Currently our license portal only supports business needs and does not allow developers to generate keys. 

Thank you @LetMeR00t for reporting this issue as it allows us to better prioritize this issue

**Comment by Kamforka** [comment]
As a first attempt I created a licensed private image and added the integration test action in #276 
You are welcome to check it out!

**Comment by Kamforka** [comment]
Closing this as it was covered in #276 and the dev licensing should be discussed with StrangeBee directly.
