### ISSUE TITLE
Getting rid of develop branch

### ISSUE THREAD

**Issue by Kamforka** [TheHive-Project/TheHive4py#293]
@nadouani I'm not sure about the usefulness of the `develop` branch.

As we're going to have proper ci checks and tests implemented soon in my opinion it is unnecessary to retain an intermediate branch.

My proposal is to work on feature branches then merge them back to master (which should be protected), then tag master to trigger a pypi deployment.

Any opposition?

**Comment by nadouani** [comment]
@Kamforka ok go ahead

**Comment by Kamforka** [comment]
Prefixed develop with ZzZ and going to clean it up at a later date.
