### ISSUE TITLE
[Tests] kamforka/thehive4py-integrator:thehive-5.2.4 doesn't exist

### ISSUE THREAD

**Issue by LetMeR00t** [TheHive-Project/TheHive4py#307]
Hello,

When I'm trying to run pytest, I have the following error (found after running the command manually):

```bash
C:\Users\tekal>docker run -d --rm -p 9000 --name thehive4py-integration-tests kamforka/thehive4py-integrator:thehive-5.2.4
Unable to find image 'kamforka/thehive4py-integrator:thehive-5.2.4' locally
docker: Error response from daemon: pull access denied for kamforka/thehive4py-integrator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Would you mind to explain how we can get access to your image to run the pytest command ?

**Comment by Kamforka** [comment]
Hi @LetMeR00t, that's unfortunately not possible at the moment as described here: https://github.com/TheHive-Project/TheHive4py#testing

For the time being please rely on the integration-tests GitHub workflow
