### ISSUE TITLE
Unable to create Observables during Alert creation or after

### ISSUE THREAD

**Issue by robj192** [TheHive-Project/TheHive4py#314]
Hello,

I'm using Thehive4py (version 2.0.0b5).

I managed to create an Alert, and after that I'm trying to create observables one by one and I'm getting a 404 error:
`thehive4py.errors.TheHiveError: NotFoundError - /api/v1/alert/~303882408/observable`

I was obtaining this error on previous versions and decided to update Thehive4py in the latest version, and the problem remained. While researching for a workaround, I found in the ReadMe of this repository that it is possible to add the observables during the alert creation.

So, I did just that, I was able to successfully create the alert (as before), but the Alert doesn't have any observables. I double-checked every attribute and unable to find anything wrong I decided to use the ReadMe example:
`        "observables": [
            {"dataType": "ip", "data": "93.184.216.34"},
            {"dataType": "domain", "data": "example.com"},
        ]`

Still, the observables were not there.

Is anyone having this problem? Anyone found a workaround?

Thanks.

**Comment by robj192** [comment]
Using `hive.observable.create_in_alert` also results in a 404 error:
`thehive4py.errors.TheHiveError: NotFoundError - /api/v1/alert/~344469536/observable`

**Comment by Kamforka** [comment]
Hi @robj192 thanks for reaching out! Can you provide us your snippet so we can try and reproduce the issue?
Also please provide your TheHive version and the user's permission you try to create the alert/observables with.

**Comment by robj192** [comment]
Hello,

I was using the snippet from the ReadMe page:
`my_alert = hive.alert.create(
    alert={
        "type": "my-alert",
        "source": "my-source",
        "sourceRef": "my-reference",
        "title": "My test alert",
        "description": "Just a description",
        "observables": [
            {"dataType": "ip", "data": "93.184.216.34"},
            {"dataType": "domain", "data": "example.com"},
        ],
    }
)`

Also, my The Hive version is 4.1.16-1.

In the end I ended up managing to get things done by creating the alert, promoting it to a case and adding the observables on the case... It's not as I wanted to, but ends up being the same, since I would promote all the Alerts anyway.

**Comment by Kamforka** [comment]
Hi @robj192 glad you could resolve the issue! However please note that your TheHive version is end of life and is not supported by the library anymore, and probably there is some discrepancy between the API endpoints that's causing your issue in the first place.

**Comment by Kamforka** [comment]
I see and that's expected as there was a major release of the TheHive and now v5.x is the latest supported major.

**Comment by robj192** [comment]
So, I guess the name "TheHive4py" is inteded to be read as "The Hive for Python" and not exactly The Hive 4 (version). Is that correct?

**Comment by Kamforka** [comment]
Very much indeed. Please consult the [readme's intro](https://github.com/TheHive-Project/TheHive4py?tab=readme-ov-file#thehive4py) section as that should clarify further.
