### ISSUE TITLE
Need ability to change task group from detault

### ISSUE THREAD

**Issue by blainedw** [TheHive-Project/TheHive4py#328]
The Hive API does not appear to have the ability to add tasks to a group like you can in the UI. When using thehive4py it will create tasks under the default group.

**Comment by Kamforka** [comment]
Hi @blainedw. Are you sure it's not doable with thehive4py already?

Have you tried something like:

```python
# to create task with non default group
hive.task.create(
    case_id="~1234", task={"group": "my-task-group", "title": "my-task"}
)

# to update existing task's group
hive.task.update(task_id="~5678", fields={"group": "my-other-group"})
```
