### ISSUE TITLE
Move to MIT license completion could have a new version release with Pypi release

### ISSUE THREAD

**Issue by jamesmckibbenathrb** [TheHive-Project/TheHive4py#332]
With the recently updated toml and our expected proper MIT license meta that should follow, could we have a new release so public pulls can use the approval/license enablement?

Current release on Pypi:
thehive4py 1.8.1

Current release on Github Repo:
thehive4py 2.0.0b5

Also, thank you for your prompt pull request response and your time and attention to this project, many appreciate it!!

**Comment by Kamforka** [comment]
Hi @jamesmckibbenathrb, I'll try to find some time and make a release this week hopefully.
