### ISSUE TITLE
Allow file observable creation from memory

### ISSUE THREAD

**Issue by ninSmith** [TheHive-Project/TheHive4py#35]
### Request Type
Feature Request

### Summary
Allow file observable creation from memory

### Description
Currently, to create a file observable, it is needed to provide the path to the file to TheHive4py.   
It would be nice to allow file observable creation from memory.
Basically, in some case, it is not well-designed to write the file to disk and then delete it "just" for observable creation.

**Comment by jojoob** [comment]
I've implemented this for creating task logs: https://github.com/kapschcdc/TheHive4py/commit/deac3608fec3f5bb7c7ba591e2abb09914a7616b
Maybe you can adopt it for observable creation.

**Comment by DarrenSykes** [comment]
It appears just to be a case of modifying models.py thus:

class CaseObservable(JSONSerializable):
    def __init__(self, **attributes):
        if attributes.get('json', False):
            attributes = attributes['json']
        self.dataType = attributes.get('dataType', None)
        self.message = attributes.get('message', None)
        self.tlp = attributes.get('tlp', 2)
        self.tags = attributes.get('tags', [])
        self.ioc = attributes.get('ioc', False)
        self.sighted = attributes.get('sighted', False)

        data = attributes.get('data', [])
        if self.dataType == 'file':
            if type(data[0]) is tuple:
                file,filename = data[0]

                #we've passed a file object, rather than a filename
                mimetype = magic.Magic(mime=True).from_buffer(file.read())

                file.seek(0)
                self.data = [{'attachment': (filename, file, mimetype)}]
            else:
                self.data = [{'attachment': (os.path.basename(data[0]), open(data[0], 'rb'), magic.Magic(mime=True).from_file(data[0]))}]
        else:
            self.data = data

**Comment by nadouani** [comment]
Hello, could you make it a PR, verify it so that I can merge it ;)

Thanks

**Comment by ehooo** [comment]
I think could be a good idea allows also set the mime-type, cause in case of the "text files" the Magic is not working very good.
