### ISSUE TITLE
Support several small functions in TheHive4py

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive4py#47]
### Request Type
Feature Request

### Problem Description
Several small functions are currently not available in TheHive4py.
Some examples, I was confronted with:
-Check for existens of an Tag attribute on a case
-Find all Tasks of a Case
-Get technical ID of UI caseID
-Get UI caseID of technical CaseId 
-Iterate over task-log entries within a task.
-Add, removed, Edit a customField

BTW: Better naming would be helpful, because caseId could be interpreted as both. in the documentation and code examples...

**Comment by npratley** [comment]
Hi @crackytsi, quick question about checking for the existence of a tag attribute on a case. The `tags` attribute of the `Case` class is just a list, so you can check that with `'tagname' in case.tags` but I can happily add a `has_tag()` method to do that if preferred.

Or did you mean to search for all cases with a given tag? If so I think you'll need to use the `find_cases()` method but I'm not exactly sure how to search by tag, would have to check the docs.

**Comment by crackytsi** [comment]
Actually both :)
The search itself is really ugly and a wrapper class could be more than usefull.
As I wrote a tool that synchronizes with TheHive I required both functionalities.
A hasTag function is of course not needed, but nice to have :)

**Comment by npratley** [comment]
Thanks for the reply. The search improvements probably need to be split out to a separate issue, I'm not familiar enough with how it works now but can have a look.

Regarding finding all Tasks of a Case, is there something that `get_case_tasks()` doesn't provide?

**Comment by crackytsi** [comment]
So as far as I see not :)

**Comment by nadouani** [comment]
@crackytsi So to answer your questions, please see below

> Check for existens of an Tag attribute on a case

You can fetch the case by ID and check its tag attribute

> Find all Tasks of a Case

You can use `TheHiveApi.get_case_tasks` method

> Get technical ID of UI caseID

You can find the case by using `TheHiveApi.find_first(query=Eq('caseId', 2))` method

> Get UI caseID of technical CaseId

You can find the case `TheHiveApi.find_first(query=Id('CASE_INTERNAL ID'))` and get the `caseId` property of it

> Iterate over task-log entries within a task.

You can use `TheHiveApi.get_task_logs` method

> Add, removed, Edit a customField

You can update the case's customField attribute (could be improved later in fact)
