### ISSUE TITLE
Query for creating alert 

### ISSUE THREAD

**Issue by setushastri93** [TheHive-Project/TheHive4py#56]
how can I generate a alert of any email of outlook, with attachment attached in that email, in the hive? , where I have to do changes for creating any alert?

**Comment by nadouani** [comment]
Hello, here is an example for creation an Alert on TheHive using TheHive4Py: https://github.com/TheHive-Project/TheHive4py/blob/master/samples/test-alert-create.py

The use of other libraries like how to get emails from outlook or how to read attachments etc... is something out of the scope of TheHive4py.

That said, you can ask the question on TheHive's Gitter channel http://gitter.im/TheHive-Project/TheHive the community will probably give you some hints.

Thanks

**Comment by setushastri93** [comment]
okey.. Thanks..
