### ISSUE TITLE
Correction in update_case usage

### ISSUE THREAD

**Issue by PavanKotikalapudi** [TheHive-Project/TheHive4py#57]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive4py version / git hash   |  1.4.2

### Problem Description
Describe the problem/bug as clearly as possible.

The current [update_case](https://github.com/TheHive-Project/TheHive4py/blob/571427661f2d0bc999bd05963cbb33d6b4aa8395/thehive4py/api.py#L102) method take an object which contains case id and other fields that need to be updated.

The [line](https://github.com/TheHive-Project/TheHive4py/blob/571427661f2d0bc999bd05963cbb33d6b4aa8395/samples/test-case-update.py#L10-L11) shows that you create a case object which unnecessarily update the defaults of the case.

### Steps to Reproduce
try to use the update method to update only a particular field of the case.

### Possible Solutions
either change the update_case method parameter to accept case_id and attributes of case to update as **kwargs or create a pojo for the update_case.

**Comment by nadouani** [comment]
Hi @npratley, can you take a look to this issue please? Thanks

**Comment by npratley** [comment]
Hi @PavanKotikalapudi thanks for the report. I don't fully understand though, the line linked to just creates the case for example purposes, `update_case` itself shouldn't modify case defaults. Can you please provide sample code showing what you would like `update_case` to do and what it is not doing correctly? Thanks!

**Comment by PavanKotikalapudi** [comment]
Sure. 

As per current [example](https://github.com/TheHive-Project/TheHive4py/blob/master/samples/test-case-update.py)

# Create a new case
case = thehive.case.create(title='From TheHive4Py', description='N/A', tlp=3, flag=True,
                           tags=['TheHive4Py', 'sample'], tasks=[])

# Save the new case's ID for later use
case_id = case.id

# Change some attributes of the new case
case.tlp = 1
case.severity = 1
case.flag = False

# Update the case
thehive.update_case(case)

the above code would update the title, description and other details though we only need to update tlp, severity and flag.

Instead if we can change the method to 

def update_case(self, case_id, **attributes):

or creating a object like this 

classs ModifiedCase(object):

    def __init__(self, caseId, **attributes_to_update):
     storing isntance variables here

then we can use current method without modifying
 
thehive.update_case( ModifiedCase( 'SomeCaseID', tlp=1)

**Comment by nadouani** [comment]
The solution we will implement to make sure the changes will not break the existing tools that use this library, we will add an optional parameter to the `update_case` method, to list the fields we want to update, example:

```
api.update_case(case, ['status', 'resolutionStatus', 'impactStatus', 'tags', 'summary'])
```
