### ISSUE TITLE
Update task

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/TheHive4py#6]
Add a method to update a task in a case

**Comment by billmurrin** [comment]
I've got a method for this in my fork already, will submit a PR.

**Comment by nadouani** [comment]
Will be fixed via #85

**Comment by sebastianfon94** [comment]
@nadouani Hi! i'm trying to use the update_case_task, but i don't know to get the task ID,do you have some example o that?

**Comment by nadouani** [comment]
How do you identify the task you want to update?

**Comment by sebastianfon94** [comment]
i'm not shure about to identify the task, i tried to use this:
`case = api.case(case_id)
api.get_case_tasks(case)`
but i get a error message

**Comment by sebastianfon94** [comment]
Specifically this one: TypeError: <thehive4py.models.Case object at 0x0000000003A76C18> is not JSON serializable

**Comment by sebastianfon94** [comment]
@nadouani I got the id of the tasks, but I'm not sure how to enter the parameters to the function update_case_task
