### ISSUE TITLE
Add the ability to search for all active observables where ioc:true without knowing caseIds

### ISSUE THREAD

**Issue by AntmanIV** [TheHive-Project/TheHive4py#62]
### Request Type
Feature Request

### Problem Description
The endpoint /api/_search is not exposed. Current methods to find observables require knowing the caseId. To find all observables which have **ioc:true** and list which case they are associated with a new function is required. 

### Possible Solutions
Add the following to api.py

    def get_IOCs(self, **attributes):
        """
        :return: list of IOCs
        ;rtype: json
        """

        # If you don't add the nparent parameter, you don't get the 'case' in the json
        req = self.url + "/api/_search?nparent=1"

        # Add range and sort parameters
        params = {
            "range": attributes.get("range", "all"),
            "sort": attributes.get("sort", [])
        }

        # Add body, pulled from gui in Chrome
        data = {
            "query":{"_and":[{"_string":"ioc:true"},{"_string":"!_type:audit AND !_type:data AND !_type:user AND !_type:analyzer AND !_type:alert AND !_type:case_artifact_job_log AND !status:Deleted"}]}
        }
        
        try:
            return requests.post(req, params=params, json=data, proxies=self.proxies, auth=self.auth, verify=self.cert)
        except requests.exceptions.RequestException as e:
            sys.exit("Error: {}".format(e))

Alternatively, exposing the /api/_search endpoint with a similar function that allows for customized queries would achieve the same end result.

### Complementary information
Attached is a Python script [iocTest.txt](https://github.com/TheHive-Project/TheHive4py/files/1640319/iocTest.txt) to drive this change (rename from .txt to .py)
The script uses username / password but could be easily adapted to use an api-key.

**Comment by mnmnc** [comment]
i think you can use function `__find_rows` for that. It basically works as if you use REST API /case/artifact/_search endpoint. You just have to submit search path. Resulting Json will contain case Id unter _parent IIRC.

**Comment by nadouani** [comment]
> i think you can use function `__find_rows` for that. It basically works as if you use REST API /case/artifact/_search endpoint. You just have to submit search path. Resulting Json will contain case Id unter _parent IIRC.

This is 100% valid.

**Comment by AntmanIV** [comment]
So, using a generalized search, it would look something like:

api = TheHiveApi("https://thehive.company.com", username, password)

refinement = {"_string":"!_type:audit AND !_type:data AND !_type:user AND !_type:analyzer AND !_type:alert AND !_type:case_artifact_job_log AND !status:Deleted"}

searchTerm = 'ioc:true'

ioc_query = {
			"_and": [
				{"_string": searchTerm},
				refinement
			]
		}
ioc_rows = api.__find_rows("/api/_search?nparent=10", query=ioc_query)

**Comment by nadouani** [comment]
No your can directly call `/api/case/artifact/_search` with `{"ioc":true}`

```
ioc_query = {"ioc":true}
api.__find_rows(`/api/case/artifact/_search?nparent=1`, query=ioc_query)
```
