### ISSUE TITLE
is there any method for create automatic alert when there's incoming email 

### ISSUE THREAD

**Issue by Masriyan** [TheHive-Project/TheHive4py#65]
is there any method for create automatic alert when there's incoming email

**Comment by nadouani** [comment]
Hello, you need to write a script that listens to you email inbox, parses you emails and create alerts using TheHive4Py like in https://github.com/TheHive-Project/TheHive4py/blob/master/samples/test-alert-create.py

**Comment by Masriyan** [comment]
thank you @nadouani ur suggestion is work
