### ISSUE TITLE
CustomFields are not updated in update_case

### ISSUE THREAD

**Issue by hawkcurry** [TheHive-Project/TheHive4py#66]
### Request Type
Bug

### Problem Description
Changes to the `customFields` attribute of a case are not sent when using `api.update_case(case)`

### Possible Solutions
Add `customFields` to the following lines, 

https://github.com/TheHive-Project/TheHive4py/blob/571427661f2d0bc999bd05963cbb33d6b4aa8395/thehive4py/api.py#L111-L114

**Comment by npratley** [comment]
Thanks for the report @hawkcurry. When https://github.com/TheHive-Project/TheHive4py/issues/57 is merged `update_case` will take a list of fields to update so you will provide `customFields` as a parameter.

**Comment by nadouani** [comment]
This is fixed by #57
