### ISSUE TITLE
How can I automate case creation using email?

### ISSUE THREAD

**Issue by setushastri93** [TheHive-Project/TheHive4py#68]
Hi team,

I want to automate my outlook shared folder emails as "cases" in TheHive. Please help me for the same.

**Comment by mnmnc** [comment]
You need to write a script that analyses outlook content and creates a data input that can be passed to thehive4py to push to backend as a case. thehive4py does not provide a solution to read your outlook emails.  
However you can easily read outlook email from the powershell level. I've dont this in the past: https://github.com/mnmnc/p0r/blob/master/src/p0r.ps1 

```powershell
$outlook = New-Object -comobject outlook.application
$namespace = $outlook.GetNameSpace("MAPI")

# GETTING PST FILE THAT WAS SPECIFIED BY THE PSTPATH VARIABLE
$pst = $namespace.Stores | ?{$_.FilePath -eq $pstPath}

# ROOT FOLDER
$pstRoot = $pst.GetRootFolder()

# SUBFOLDERS
$pstFolders = $pstRoot.Folders

# PERSONAL SUBFOLDER
$personal = $pstFolders.Item("Personal")

# INBOX FOLDER 
$DefaultFolder = $namespace.GetDefaultFolder(6)

# INBOX SUBFOLDERS
$InboxFolders = $DefaultFolder.Folders

# DELETED ITEMS
$DeletedItems = $namespace.GetDefaultFolder(3)

# EMAIL ITEMS
$Emails = $DefaultFolder.Items

# PROCESSING EMAILS
Foreach ($Email in $Emails) {
    # Do stuff here to get email data.
    # Output data to a file, then parse it withing a python script that uses thehive4py
}
```

**Comment by nadouani** [comment]
Fetching the emails is not the responsibility of TheHive4py, so you need a script that listens to an mailbox, extracts the details and user `create_case` function to create the case.

You can also check the following opensource tool written by @xme: https://github.com/xme/dockers/tree/master/imap2thehive
