### ISSUE TITLE
Tasks missing for creating case using a template

### ISSUE THREAD

**Issue by neok0** [TheHive-Project/TheHive4py#69]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu, 
| OS version (client)       |  10, 
| TheHive4py version / git hash   | 1.4.3

### Problem Description
There seems to be a problem with creating a case from a template. 
If the template contains a task, it does not appear in the created task.

### Steps to Reproduce
1. create a case template containing a task
2. fetch the case template via 
3. create a new case using the template
4. check TheHive. Task is missing in the case.

### Possible Solutions
        # if self.template.get('tasks', []):
        #     tasks.extend(self.template.get('tasks', []))
        #
in Case class init adds the template tasks.

**Comment by nadouani** [comment]
Hello,

I've just tested this:

```
api = TheHiveApi('http://127.0.0.1:9000', 'API_KEY')

case = Case(title='From TheHive4Py based on the Phishing template', description='N/A', tlp=2, template='Phishing')

response = api.create_case(case)
```

and it creates a case with the task of the Phishing template. So it's working.

**Comment by prabhjot25** [comment]
When we create case template using create case template function along with its tasks , then the tasks are not included in the case after the case is created from the case template

**Comment by slw07g** [comment]
There’s an intermittent issue where creating the tasks seems to silently fail
