### ISSUE TITLE
find_cases query on custom field (for template cases)

### ISSUE THREAD

**Issue by franofcholet** [TheHive-Project/TheHive4py#72]
Is it possible to use the find_cases function to query on template cases regarding the custom fields ?

In case not, is it possible to write my own function to do it using the API ?

I have a crappy solution consisting in querying all the cases and then filter the cases matching to my query but it spend lot of memory.

**Comment by nadouani** [comment]
Hello,

You can find some examples below:

- Find cases where `businessRisk` custom field equals `HIGH`
```
query = {"customFields.businessRisk.string": 'HIGH'}
api.find_cases(query=query, range=range, sort=sort)
```

- Find cases here `cvss` custom field is higher than `6``
```
query = {"_gt": {"customFields.cvss.number": 0}}
api.find_cases(query=query, range=range, sort=sort)
```

Note that the JSON field name of a custom field is `customFields.THE_NAME_OF_CF.THE_TYPE_OF_CF`
