### ISSUE TITLE
Retrieve analyzer report after analysis [question]

### ISSUE THREAD

**Issue by francoisihry** [TheHive-Project/TheHive4py#75]
I launch an analyzer on an IOC with the run_analyzer function, that works fine.
Now I would like to wait for the end of the analysis and retrieve the report.

I have been looking for the Cortex API documentation to write my own functions but I could not find the documentation https://github.com/TheHive-Project/CortexDocs : API Documentation (OUTDATED, will be updated soon)

Do you have any advice ?

**Comment by francoisihry** [comment]
Anyone ?

**Comment by remiallain** [comment]
https://github.com/Cyberprotect/TheHiveDocs/blob/master/api/connectors/cortex/job.md

**Comment by francoisihry** [comment]
Thanks RemiAllain, I tested these requests using my cortexJobId "AWOXyd38J1pkihtegvrt" :
```
test@test-VirtualBox:~$ curl --header "Authorization:Bearer 3NFVbpT+Jo9QoMHHWaB2J2v6QpCNpZfn" -X GET "127.0.0.1:9000/api/connector/cortex/job/:AWOXyd38J1pkihtegvrt"
{"type":"NotFoundError","message":"case_artifact_job :AWOXyd38J1pkihtegvrt not found"}
```

However the cortexJobId do exists because I can see it in the search request :
```
test@test-VirtualBox:~$ curl --header "Authorization:Bearer 3NFVbpT+Jo9QoMHHWaB2J2v6QpCNpZfn" -X POST "127.0.0.1:9000/api/connector/cortex/job/_search"
[{"createdAt":1527260247043,"analyzerId":"04475e23a038699a0a9b9bec059fa0f3","startDate":1527260247043,"analyzerDefinition":"Verify_DKIM_1_0","createdBy":"admin","analyzerName":"Verify_DKIM_1_0","cortexJobId":"AWOXzfAFJ1pkihtegvtm","cortexId":"local","artifactId":"4b5fdb73d673c432f04b3aaa71ed2b7f","status":"Success","endDate":1527260249233,"updatedBy":"admin","updatedAt":1527260249234,"_type":"case_artifact_job","_routing":"AWOXzcD_J1pkihtegvtb","_parent":"4b5fdb73d673c432f04b3aaa71ed2b7f","_id":"AWOXzfQEJ1pkihtegvtn","_version":2,"id":"AWOXzfQEJ1pkihtegvtn"},{"analyzerId":"04475e23a038699a0a9b9bec059fa0f3","createdAt":1527260169816,"analyzerDefinition":"Verify_DKIM_1_0","cortexJobId":"AWOXzMKUJ1pkihtegvsa","createdBy":"admin","artifactId":"14b4fe6256c7e331a0b241825e9d7933","analyzerName":"Verify_DKIM_1_0","cortexId":"local","startDate":1527260169816,"status":"Success","endDate":1527260171950,"updatedBy":"admin","updatedAt":1527260171950,"_type":"case_artifact_job","_routing":"AWOXzJgxJ1pkihtegvsQ","_parent":"14b4fe6256c7e331a0b241825e9d7933","_id":"AWOXzMZdJ1pkihtegvsb","_version":2,"id":"AWOXzMZdJ1pkihtegvsb"},{"artifactId":"ccb6f239b157a2ee529a5b0bcd48bc75","analyzerId":"04475e23a038699a0a9b9bec059fa0f3","analyzerDefinition":"Verify_DKIM_1_0","startDate":1527259980201,"createdBy":"admin","cortexJobId":"AWOXyd38J1pkihtegvrt","analyzerName":"Verify_DKIM_1_0","cortexId":"local","createdAt":1527259980200,"status":"Success","endDate":1527259985340,"updatedBy":"admin","updatedAt":1527259985342,"_type":"case_artifact_job","_routing":"AWOXyauqJ1pkihtegvri","_parent":"ccb6f239b157a2ee529a5b0bcd48bc75","_id":"AWOXyeHEJ1pkihtegvru","_version":2,"id":"AWOXyeHEJ1pkihtegvru"}]
```
And I need the Report API, but it gives 404 error : https://github.com/Cyberprotect/TheHiveDocs/blob/master/api/connectors/cortex/report.md

**Comment by remiallain** [comment]
`curl --header "Authorization:Bearer 3NFVbpT+Jo9QoMHHWaB2J2v6QpCNpZfn" -X GET "127.0.0.1:9000/api/connector/cortex/job/AWOXyd38J1pkihtegvrt"`
remove the ":" after job/

**Comment by remiallain** [comment]
The report will be in the response ;)

**Comment by francoisihry** [comment]
I had already tried without the ":" with the request you just gave, but I still receive the response :
`{"type":"NotFoundError","message":"case_artifact_job AWOXyd38J1pkihtegvrt not found"}`

And the cortexJobId "AWOXyd38J1pkihtegvrt" do appear on my search...

**Comment by remiallain** [comment]
Try with AWOXzfQEJ1pkihtegvtn

**Comment by francoisihry** [comment]
It works !!!!

**Comment by francoisihry** [comment]
Ok I will take id instead of cortexJobId, many thanks RemiAllain, you made my day ! :)
