### ISSUE TITLE
xsrf-token in theHive4py

### ISSUE THREAD

**Issue by yojo3000** [TheHive-Project/TheHive4py#76]
### Problem Description
Hi !
Is there any solution to get "xserf-token" in theHive4py?

I'm trying to do auto-analyze after the creation of a case

And I wrote a funcion in the "api.py" file

```python
 def do_analyze(self, cortex_id, observable_id, analyzer_id):

        req = self.url + '/api/connector/cortex/job'
        print ("request url: " + req)

        my_job = {
            "cortexId": cortex_id,
            "artifactId": observable_id,
            "analyzerId": analyzer_id
        }

       my_header = {
            "X-XSRF-TOKEN": ''....",
            "Cookie": "...."
       }
        try:
            response = requests.post(req, headers=my_header, data=my_job, proxies=self.proxies, verify=self.cert)
        except Exception as e:
            return e
```

Now I have to use tools like burp suite to get the "XSRF-TOKEN" and "Cookie" from web interface

It works but not a convenient way

**Comment by yojo3000** [comment]
I use api key to do auth  in the beginning

```python
api = TheHiveApi('ip address', 'my api key')
response = api.do_analyze(cortex_id, observable_id, analyzer_id)
```

but theHive will return 401 auth error before I add those headers

other built-in functions in "api.py " like "create_case" or "get_case" work fine in this way

**Comment by nadouani** [comment]
the following code is not needed:

```
my_header = {
            "X-XSRF-TOKEN": ''....",
            "Cookie": "...."
       }
```
