### ISSUE TITLE
What does mean this error?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive4py#81]
I'm receiving this error while trying to add observables to a newly created case via the API:
```
[WARNING] Cannot add observable isc_ticket: 3480094 - 400 ({"tableName":"case_artifact","type":"AttributeCheckingError","errors":[[{"name":"case_artifact.dataType","format":"enumeration","value":{"type":"JsonInputValue","value":"isc_ticket"},"type":"InvalidFormatAttributeError","message":"Invalid format for case_artifact.dataType: JsonInputValue(\"isc_ticket\"), expected enumeration"}]]}
```

Here is the code:
```
for o in observables:
    observable = CaseObservable(
    dataType = o['type'],
    data     = o['value'],
    tlp      = int(config['caseTLP']),
     ioc      = False,
    tags     = config['caseTags'],
    message  = 'Found in the email body'
)
response = api.create_case_observable(newID, observable)
```
Any idea? I'm using the same technique to add observables to alerts and it works...
Tx!

**Comment by saadkadhi** [comment]
@nadouani can you look into it please?

@xme sorry for the slow response but we are still on holidays as indicated in our latest blog post.

**Comment by nadouani** [comment]
@xme This error means, `isc_ticket` is not part of the observable datatype's enumeration. Is `isc_ticket` a valid data type?

**Comment by xme** [comment]
Indeed, it was simply not defined, sorry for the noise... Enjoy holidays ;-)
