### ISSUE TITLE
Unable to close case as TruePositive WithImpact

### ISSUE THREAD

**Issue by mnmnc** [TheHive-Project/TheHive4py#93]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | Fedora
| TheHive4py version   |  1.5.1

### Problem Description
Unable to close case with api.update_case().

### Steps to Reproduce
1. consider following code:
```python
c = api.case(caseid)
c.status = 'Resolved'
c.description = 'test'
c.resolutionStatus = 'TruePositive'
c.impactStatus = 'WithImpact'
resp = api.update_case(c)
```
2. This code should result in case being closed, however endpoint respond with modified case (description is updated correctly), but not closed. 

### Possible Solutions
I think this has something to do with the fact that `api.case()` return object does not have all case fields included. Maybe `api.update_case` does not verify/check all fields when updating the case?

Problem is non existing when I use `requests.patch()`.

**Comment by nadouani** [comment]
I think you need to set a `summary` to your case

**Comment by nadouani** [comment]
Weird, I don't see `status` listed in `api.update_case` in fact. I'll take a look right now ;)
