### ISSUE TITLE
Add ability to specify arbitrary short report data for observable

### ISSUE THREAD

**Issue by mnmnc** [TheHive-Project/TheHive4py#98]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat, 
| OS version (client)       | Ubuntu, 

### Problem Description
It would be very helpful if it would be possible to add a short analyzer report to the observable via API without running an analyzer on cortex.  
Simply to specify json or a string that should be displayed as a report for observable - just like a tag.  
The advantage over tags would be that reports are color marked based on severity or findings.  
Thanks to that custom enrichers that do not have to rely on cortex could be incorporated into TheHive environment.  

### Possible Solutions
report = { title: report_title, score: value, designation: malicious / suspicious / benign }  
api.observable.add_report(observable_id, report)  

### Complementary information
I've wrote a lot of enrichers that do not rely on cortex (contenerized scripts) and I realy think it would be beneficial to allow for a custom reports for observables.

**Comment by nadouani** [comment]
the `reports` attribute is dedicated to results from Cortex. It's not a good idea to introduce custom label in it. We wanted to keep it dedicated to Cortex analysis results.
